### ISSUE TITLE
💡 [REQUEST] - <Queries not utilizing JPQL>

### ISSUE THREAD

**Issue by ktha423** [SE310-Team1/ShoppIt#100]
### Summary

Queries for items are not utilizing JPQL to narrow down what's retrieved. Rewriting JPQL queries to be more specific will make retrieving and working with database items in code base easier. 

### Basic Example

Example: being able to retrieve items based on their attributes properly, instead of just getting all database items from the database.

**Comment by ochu761** [comment]
Good issue! Would be good to fully utilise JPQL instead of getting all items and filtering in Java

**Comment by ochu761** [comment]
Closed by #104
