### ISSUE TITLE
💡 [REQUEST] - Delete Item class and use FoodItem class

### ISSUE THREAD

**Issue by ochu761** [SE310-Team1/ShoppIt#101]
### Summary

Item class currently acts as a middleman between FoodItem and the shopping list (currently just a list view, ShoppingList model class needed #97). 

Item references/is associated with a list view, however, this association should be one-way from the ShoppingList. i.e: the ShoppingList should be responsible for referencing the Item, not the other way around.

### Basic Example

- [ ] Rewrite Item class usages to FoodItem
- [ ] Move relevant Item implementation to FoodItem (remove association to list views)
- [ ] Delete Item class

**Comment by poli648** [comment]
This will work great with the new shopping list class, a great opportunity to clean up code.
