### ISSUE TITLE
💡 [REQUEST] - <connect database with model classes using hibernate>

### ISSUE THREAD

**Issue by WiktorTumilowicz** [SE310-Team1/ShoppIt#11]
### Start Date

11/8/2022

### Implementation PR

#30 #49

### Summary

Using hibernate connect the database to the model classes

### Basic Example

Configuration con = new Configuration().configure().addAnnotatedClass(Food.class);

        ServiceRegistry registry = new StandardServiceRegistryBuilder().applySettings(con.getProperties()).build();

        SessionFactory sessionFactory = con.buildSessionFactory(registry);
        Session session = sessionFactory.openSession();
        Transaction tx = session.beginTransaction();

        session.save(food);

        tx.commit();

### Drawbacks

only one person currently knows how to use derby and hibernate and i will probably have to teach others how to use them

**Comment by scho518** [comment]
Dependent on #10.
