### ISSUE TITLE
💡 [REQUEST] - Display Shopping List as FXML card view in Main Screen(with details)

### ISSUE THREAD

**Issue by ochu761** [SE310-Team1/ShoppIt#110]
### Summary

Displaying list as FXML card view item with details in the Main screen ListView. Needs to include a listener for an on click (MouseEvent).

### Basic Example

- Refer to implementation for FoodItems card view

**Comment by mmcc944** [comment]
Card views are a good idea as they allow us to style them and make the application look nice. Good note about the on click listeners that is required
