### ISSUE TITLE
💡 [REQUEST] - Style food items list view

### ISSUE THREAD

**Issue by mmcc944** [SE310-Team1/ShoppIt#111]
### Summary

Food items shown in the searchpopupcontroller have minimal styling added to them

- [ ] Add extra details such as price and calories per weight
- [ ] Change colour patterns and ensure consistency with the entire application

### Basic Example

Add extra labels to each card view
Change font size and colour of label texts

**Comment by poli648** [comment]
Yes, these changes would make the app feel much more fleshed out and valuable. Great Thinking!
