### ISSUE TITLE
💡 [REQUEST] - Saving list information inputted on the newListScene to shoppingList 

### ISSUE THREAD

**Issue by poli648** [SE310-Team1/ShoppIt#112]
### Start Date

10/14/2022

### Implementation PR

NA

### Reference Issues

NA

### Summary

Want to add the functionality to set a name and description from the newListScene and have it saved to a shopping list. This should also work with the edit list scene.

### Basic Example

When a title is input into the title bar on newListScene, it Is saved

### Drawbacks

NA

### Unresolved questions

How will it be done?

**Comment by ochu761** [comment]
Good issue! This is vital functionality needed to allow the user to add relevant details to their shopping lists.
