### ISSUE TITLE
🐛 [BUG] - SearchPopUpScene resize bug

### ISSUE THREAD

**Issue by samanthamebius** [SE310-Team1/ShoppIt#114]
### Description

When the SearchPopUpScene is opened and resized multiple page elements do not resize as expected with the window. 

Tasks:

- [ ] Back arrow remains fixed distance from the left
- [ ] ListView resizes to fill most of the window
- [ ] TextField expands across the window when the window is stretched horizontally 
- [ ] 'Select an Item' text remains horizontally central when resized

### Reproduction URL

f366d4384ce2c5041afd8c0fe72dc4e956d6582d

### Reproduction steps

```bash
1. Click on the 'Add New List' button on the main screen
2. Click on the 'Add Item' button on the New List screen
3. Resize the window
```

### Screenshots
Prior to resize
<img width="798" alt="Screen Shot 2022-10-15 at 1 22 53 AM" src="https://user-images.githubusercontent.com/79612950/195846115-6a8d5a0d-d4b2-40c7-8e28-eeeaadf83138.png">

After resize
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/79612950/195846225-8ae7426c-8486-4b84-bb5d-9151c546c138.png">

### Logs

```bash
Not relevant here
```

### OS

Mac

**Comment by poli648** [comment]
Yes, it will be good to have this bug sorted out. Will make the UI much cleaner.

**Comment by ochu761** [comment]
Outdated, will be readdressed in #125
