### ISSUE TITLE
💡 [REQUEST] - <Database entries are not in displayed in any particular order>

### ISSUE THREAD

**Issue by ktha423** [SE310-Team1/ShoppIt#115]
### Summary

Currently, the list being displayed from the database in terms of food items are in a random order or are being displayed in order of when they were added. 

### Basic Example

Carrots being higher up in the list order than avocado

Want to ensure that it is alphabetical ordering

**Comment by ochu761** [comment]
Good feature to add! Would help the user to find items in the list more easily.
