### ISSUE TITLE
💡 [REQUEST] - Remove item image backgrounds

### ISSUE THREAD

**Issue by samanthamebius** [SE310-Team1/ShoppIt#120]
### Start Date

18/10/2022

#121 

_No response_

### Summary

The backgrounds of the item images currently vary in colour. These backgrounds should be removed so that the item images can be used consistently across the application without affecting the aesthetic. 

### Basic Example

The following image
![greek_yogurt](https://user-images.githubusercontent.com/79612950/196303618-a6fdbb27-8957-4e1c-8bb7-6fd41ccdd0af.jpg)
will become
![greek_yogurt](https://user-images.githubusercontent.com/79612950/196303556-5c416556-cde7-45aa-b743-6719137b2465.png)

**Comment by mmcc944** [comment]
Good idea. Some consistency in images would be great
