### ISSUE TITLE
🐛 [BUG] - Fix main scene going into list not working

### ISSUE THREAD

**Issue by jzho987** [SE310-Team1/ShoppIt#123]
### Description

when clicking into a list from the main scene, the list scene does not load properly. Bug likely introduced from pr #107 .

### Reproduction URL

https://github.com/SE310-Team1/ShoppIt/pull/107

### Reproduction steps

```bash
1. Go to the main scene of the application
2. Click on any list in "Your Lists"
4. See error "failed to lazily initialize a collection of role: database.models.ShoppingList.items: could not initialize proxy - no Session"
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### OS

Windows

**Comment by samanthamebius** [comment]
Will be good to get this fixed!
