### ISSUE TITLE
💡 [REQUEST] - Tidy up CSS and UI Inconsistencies

### ISSUE THREAD

**Issue by ochu761** [SE310-Team1/ShoppIt#125]
### Start Date

18/10/2022

### Implementation PR

#134 

### Summary

- [x] Some styling is still found in the FXML file. Would be good to have them all centralised in a single CSS file.
- [x] Check and fix UI inconsistencies across screens
- [x] Change food item border
- [x] Restrict window resizing to only vertical

### Basic Example

Move FXML styling in #111 to CSS file
https://github.com/SE310-Team1/ShoppIt/pull/118#discussion_r997585145

**Comment by jzho987** [comment]
Good to do at the end to improve the quality and user experience! Approved.
