### ISSUE TITLE
🐛 [BUG] - Title and Description not showing in IndividualListScene

### ISSUE THREAD

**Issue by ochu761** [SE310-Team1/ShoppIt#128]
### Description

Title and description of a list in the IndividualListScene is not displayed (shows default "List title")

Using InfoStore instance:
- [x] Set title 
- [x] Set description

### Reproduction URL

https://github.com/SE310-Team1/ShoppIt/commit/8d1bc3887dc9039a69688d0107380e57302fbab1

### Reproduction steps

```bash
1. Add a new list
2. Goto Main screen 
3. Open a list
4. Edit list title and description
5. Open the list again
6. Observe the unchanged list title and description
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by samanthamebius** [comment]
It will be good for this information to be displayed
