### ISSUE TITLE
🐛 [BUG] - Title and description reset when add item to list

### ISSUE THREAD

**Issue by poli648** [SE310-Team1/ShoppIt#129]
### Description

When adding an item to a shopping list the previously added title and description are removed from the newIduvidualList scene 

### Reproduction URL

https://github.com/SE310-Team1/ShoppIt

### Reproduction steps

```bash
1. Go to newInduvidualList scene
2. Type in a title or description 
3. Click on add new item and then add an item
4. See error
```

### Screenshots

```bash
NA
```

### Logs

```bash
NA
```

### OS

Windows

**Comment by ochu761** [comment]
Good issue! Title and description are not saved when navigating out of edit/add list (to add item). Would be good to persist this.
