### ISSUE TITLE
🐛 [BUG] - <Window resize responsive>

### ISSUE THREAD

**Issue by mmcc944** [SE310-Team1/ShoppIt#73]
### Description

Features do not appear within the window when opening the application. To be able to see them the window has to be full screen. Even though the window is fullscreen there are also instances of the button being cut off at the bottom.

- [x] All elements are within the selected window size
- [x] Size of the buttons should be appropriate for the window size 

### Reproduction URL

main branch

### Reproduction steps

```bash
1. Run the program
2. See what is within the window
3. Make the window fullscreen
4. Notice button is now visible
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

**Comment by samanthamebius** [comment]
Good issue, something that definitely needs to be addressed!
