### ISSUE TITLE
💡 [REQUEST] - Add navigation across application 

### ISSUE THREAD

**Issue by samanthamebius** [SE310-Team1/ShoppIt#76]
### Start Date

27/09/22

### Implementation PR

#80

### Summary

Add buttons to allow the user to navigate between all appropriate scenes in the application. 

- [X] Back button from the search menu
- [X] Rename buttons to be more descriptive 

### Basic Example

Not required

### Drawbacks

New buttons will need to be worked into the resize responsive version of the application that is being worked on at present

**Comment by ochu761** [comment]
Sounds good! Would be great to implement this to make testing other screens easier as well.
