### ISSUE TITLE
💡 [REQUEST] - Create list model class

### ISSUE THREAD

**Issue by poli648** [SE310-Team1/ShoppIt#90]
### Start Date

09/29/2022

### Implementation PR

To be referenced

### Reference Issues

This issue

### Summary

Shopping list model class needs to be added to allow storing and displaying of lists in the future.

### Basic Example

An example ShoppingList could be 
title = "My shopping list" 
description = "my weekly shopping list -have to buy some carrots!"
itemList = {carrotItem}

### Drawbacks

Will not be incorporated into the database yet, so is not permanent. 

### Unresolved questions

How can we implement it into the database?

**Comment by ochu761** [comment]
Sounds good! There does not currently seem to be a way to store the list itself, so a model class would be excellent.

Will need to consider whether we persist this list to the database, or store as a separate local file (.txt)
