### ISSUE TITLE
💡 [REQUEST] - Adding storing list functionality 

### ISSUE THREAD

**Issue by poli648** [SE310-Team1/ShoppIt#94]
### Start Date

09/29/2022

### Implementation PR

Not reference yet

### Reference Issues

Can't save lists

### Summary

The lists that are displayed in the new list scene are not saved anywhere once the new list scene is closed

### Basic Example

Add items to a list and then save the list. None of the data is saved

### Unresolved questions

Will these lists be saved to the database.

**Comment by ochu761** [comment]
Good issue, this is vital functionality for the app and it would be great for it to be implemented!
