### ISSUE TITLE
💡 [REQUEST] - Add Shopping list model class

### ISSUE THREAD

**Issue by poli648** [SE310-Team1/ShoppIt#97]
### Start Date

10/05/2022

### Implementation PR

NA

### Reference Issues

NA

### Summary

Addition of a new shopping list model class to better store list information

### Basic Example

Shopping List
-Title: My shopping list
-Description: This is my shopping list
-Items: {Carrot, Bannana}
-ItemQuantity: <Carrot, 2>, <Bannana, 1>

### Drawbacks

Adds new entity to the database that we have to work around

### Unresolved questions

How will this effect query times?

**Comment by ktha423** [comment]
Sounds like a good issue, approved.
