### ISSUE TITLE
💡 [REQUEST] - Refactor styling method

### ISSUE THREAD

**Issue by samanthamebius** [SE310-Team1/ShoppIt#98]
### Implementation PR

#103 

### Summary

Presently, all scenes in the application are styled individual via fxml. This refactor would include centralising the styling to one or very few CSS styling sheets to make the styling across the application more consistent and easier to modify. 

### Basic Example

Removing the css styling properties that are used commonly across the application and defining these in a styling sheet.

**Comment by ochu761** [comment]
Good issue! Current styling methods are inconsistent throughout the application (uses either CSS or directly in the FXML files). Would be very beneficial to have all styling come from CSS only.

Current refactoring plans seem to only be modifying the classes, not the FXML. So modifying this side of the application should not result in any conflicts as long as:
- FXML element ids are not changed
- FXML elements are not deleted
