### ISSUE TITLE
💡 [REQUEST] - Refactor database sessions

### ISSUE THREAD

**Issue by mmcc944** [SE310-Team1/ShoppIt#99]
### Summary

Open database sessions only when required rather than at the start of the application. try-catch-finally to close the session when needed.

Possible fix: declare SessionFactory instead of Session in Main.

### Basic Example

try {
      DatabaseManager em = ...
} finally {
      em.close()
}

**Comment by ochu761** [comment]
Good issue! Sessions should only be opened when necessary and closed after the transaction is complete. This would be more robust

**Comment by jzho987** [comment]
Issue closed from pr #107
